[mypy]
python_version = 3.12
plugins = mypy_django_plugin.main
check_untyped_defs = True
warn_unused_ignores = True
warn_redundant_casts = True
show_error_codes = True
ignore_missing_imports = True
disable_error_code = var-annotated, has-type, attr-defined, assignment, misc

[mypy.plugins.django-stubs]
django_settings_module = config.settings.test
strict_settings = true
